import Head from 'next/head';
import styles from '../styles/Home.module.css' 
import { app } from '../firebase';
import {
    TextField,
    Button
} from '@mui/material';
import { useEffect, useState } from 'react';
import {
    createUserWithEmailAndPassword,
    getAuth,
    signInWithPopup,
    GoogleAuthProvider,
    GithubAuthProvider
} from 'firebase/auth';
import { useRouter } from 'next/router';

export default function Register() {
    const auth = getAuth();
    const router = useRouter();
    const googleProv = new GoogleAuthProvider();
    const githubProv = new GithubAuthProvider();

    const [email,setEmail] = useState('')
    const [password,setPassword] = useState('')
    
    const Signup = () => {
        createUserWithEmailAndPassword(auth,email,password)
            .then (res => {
                router.push('/')
                sessionStorage.setItem('Token', res.user.accessToken)
            })
            .catch(err => {
                console.log(err.message);
            })
    }

    const signUpWithGoogle = () => {
        signInWithPopup(auth,googleProv)
            .then(res => {
                sessionStorage.setItem('Token', res.user.accessToken)
                router.push('/')
            })
            .catch(err => {
                console.log(err.message);
            })
    }

    const signUpWithGithub = () => {
        signInWithPopup(auth,githubProv)
            .then(res => {
                sessionStorage.setItem('Token', res.user.accessToken)
                router.push('/')
            })
            .catch(err => {
                console.log(err.message);
            })
    }

    useEffect(() => {
        let token = sessionStorage.getItem('Token');
        if(token) {
            router.push('/')
        }
    },[])
    return (
        <>
            <Head>
                <title>CRUD Firestore</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Register</h1> 
                <TextField id='email' type='email'
                label='email' placeholder='email' margin='normal'
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                />
                <TextField id='password' type='password'
                label='password' placeholder='password'
                value={password} margin='normal'
                onChange={(e) => setPassword(e.target.value)} 
                />
                <Button variant='contained' onClick={Signup}>Signup</Button>
                <Button variant='contained' sx={{marginBlock : '5px'}} onClick={signUpWithGoogle}>Signup with Google</Button>
                <Button variant='contained' onClick={signUpWithGithub}>Signup with Github</Button>
            </main>
        </>
    )
}